[tool.poetry]
name = "mortier"
version = "0.1.0"
description = ""
authors = ["Epsilon"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
svgwrite = "^1.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
